// lib/merchantData.js — Realistic Fintech Merchant Data & Branding

export const REALISTIC_TRANSACTIONS = [
  {
    transaction_id: 'txn_razor_9824',
    merchant_name: 'Netflix India',
    merchant_category: 'subscription',
    amount: 649,
    status: 'recovered',
    failure_reason: 'insufficient_funds',
    payment_method: 'card',
    customer_segment: 'returning',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-29 18:42',
    ml_result: { success_probability: 0.88, shap_contributions: [{ feature: 'is_near_payday', impact: 0.24 }, { feature: 'historical_failure_rate', impact: 0.12 }] },
    customer_message: 'Your Netflix subscription payment of ₹649 was automatically recovered. No action needed.',
  },
  {
    transaction_id: 'txn_razor_8711',
    merchant_name: 'Amazon Web Services',
    merchant_category: 'cloud_saas',
    amount: 14890,
    status: 'recovered',
    failure_reason: 'processing_error',
    payment_method: 'netbanking',
    customer_segment: 'high_value',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-29 17:15',
    ml_result: { success_probability: 0.94, shap_contributions: [{ feature: 'time_since_last_attempt_hours', impact: 0.31 }] },
    customer_message: 'Your AWS monthly billing invoice was successfully re-authorized by Razorpay Recovery Engine.',
  },
  {
    transaction_id: 'txn_razor_7640',
    merchant_name: 'Apple Services',
    merchant_category: 'digital_goods',
    amount: 999,
    status: 'retrying',
    failure_reason: 'issuer_declined',
    payment_method: 'card',
    customer_segment: 'returning',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-29 16:30',
    ml_result: { success_probability: 0.62, shap_contributions: [{ feature: 'is_recurring', impact: 0.15 }] },
    customer_message: 'Your Apple One subscription retry is scheduled for optimal payday window.',
  },
  {
    transaction_id: 'txn_razor_6522',
    merchant_name: 'Spotify Premium',
    merchant_category: 'subscription',
    amount: 119,
    status: 'recovered',
    failure_reason: 'insufficient_funds',
    payment_method: 'upi',
    customer_segment: 'new',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-29 15:10',
    ml_result: { success_probability: 0.79, shap_contributions: [{ feature: 'is_near_payday', impact: 0.28 }] },
    customer_message: 'Your Spotify AutoPay UPI mandate was successfully processed on attempt 2.',
  },
  {
    transaction_id: 'txn_razor_5419',
    merchant_name: 'Uber Technologies',
    merchant_category: 'mobility',
    amount: 450,
    status: 'failed',
    failure_reason: 'card_stolen',
    payment_method: 'card',
    customer_segment: 'new',
    attempt_count: 1,
    max_attempts: 1,
    date: '2026-08-29 14:05',
    ml_result: { success_probability: 0.02, shap_contributions: [{ feature: 'card_stolen_rule', impact: -0.85 }] },
    customer_message: 'Payment declined due to security flag. Please update payment method.',
  },
  {
    transaction_id: 'txn_razor_4308',
    merchant_name: 'Notion SaaS Enterprise',
    merchant_category: 'cloud_saas',
    amount: 4999,
    status: 'recovered',
    failure_reason: 'do_not_honor',
    payment_method: 'card',
    customer_segment: 'high_value',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-29 12:48',
    ml_result: { success_probability: 0.81, shap_contributions: [{ feature: 'historical_failure_rate', impact: 0.22 }] },
    customer_message: 'Your Notion workspace renewal payment of ₹4,999 has been successfully recovered.',
  },
  {
    transaction_id: 'txn_razor_3290',
    merchant_name: 'Swiggy One',
    merchant_category: 'membership',
    amount: 299,
    status: 'recovered',
    failure_reason: 'network_timeout',
    payment_method: 'upi',
    customer_segment: 'returning',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-29 11:20',
    ml_result: { success_probability: 0.91, shap_contributions: [{ feature: 'payment_method_upi', impact: 0.35 }] },
    customer_message: 'Swiggy One membership renewal succeeded via automated smart retry.',
  },
  {
    transaction_id: 'txn_razor_2184',
    merchant_name: 'Flipkart VIP',
    merchant_category: 'ecommerce',
    amount: 1499,
    status: 'retrying',
    failure_reason: 'insufficient_funds',
    payment_method: 'card',
    customer_segment: 'returning',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-29 09:15',
    ml_result: { success_probability: 0.74, shap_contributions: [{ feature: 'is_near_payday', impact: 0.18 }] },
    customer_message: 'Smart retry cycle 2 queued for execution near customer payday.',
  },
]
