// lib/merchantData.js — Realistic Fintech Merchant Data, Audit Logs & Compliance Telemetry

export const REALISTIC_TRANSACTIONS = [
  {
    transaction_id: 'txn_rzp_9842',
    merchant_name: 'Netflix India',
    merchant_category: 'subscription',
    amount: 649,
    status: 'recovered',
    failure_reason: 'insufficient_funds',
    payment_method: 'card',
    customer_segment: 'returning',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 09:42',
    ml_result: {
      success_probability: 0.88,
      shap_contributions: [
        { feature: 'is_near_payday', impact: 0.24 },
        { feature: 'historical_failure_rate', impact: 0.12 },
      ],
    },
    customer_message: 'Your Netflix subscription payment of ₹649 was automatically recovered. No action needed.',
    compliance_status: 'compliant',
    attempt_timeline: [
      {
        attempt_number: 1,
        attempt_timestamp: '2026-08-29 09:42',
        channel: 'auto_retry',
        intervention_type: 'Direct Gateway Re-auth',
        outcome: 'fail',
        amount: 649,
        reason_or_stopping: 'Insufficient funds (Transient decline)',
        compliance_flags: 'Compliant (9:42 AM IST)',
      },
      {
        attempt_number: 2,
        attempt_timestamp: '2026-08-30 09:42',
        channel: 'auto_retry',
        intervention_type: 'Smart Payday Window Backoff',
        outcome: 'success',
        amount: 649,
        reason_or_stopping: 'Recovered successfully on 24h backoff schedule',
        compliance_flags: 'Compliant (9:42 AM IST)',
      },
    ],
  },
  {
    transaction_id: 'txn_rzp_8731',
    merchant_name: 'Amazon Web Services',
    merchant_category: 'cloud_saas',
    amount: 18490,
    status: 'recovered',
    failure_reason: 'processing_error',
    payment_method: 'netbanking',
    customer_segment: 'high_value',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-30 09:15',
    ml_result: {
      success_probability: 0.94,
      shap_contributions: [
        { feature: 'time_since_last_attempt_hours', impact: 0.31 },
      ],
    },
    customer_message: 'Your AWS monthly cloud infrastructure invoice was successfully re-authorized by Razorpay Recovery Engine.',
    compliance_status: 'compliant',
    attempt_timeline: [
      {
        attempt_number: 1,
        attempt_timestamp: '2026-08-30 09:15',
        channel: 'auto_retry',
        intervention_type: 'Instant Network Fallback',
        outcome: 'success',
        amount: 18490,
        reason_or_stopping: 'Recovered on immediate gateway glitch retry',
        compliance_flags: 'Compliant',
      },
    ],
  },
  {
    transaction_id: 'txn_rzp_7650',
    merchant_name: 'Apple Services',
    merchant_category: 'digital_goods',
    amount: 999,
    status: 'retrying',
    failure_reason: 'issuer_declined',
    payment_method: 'card',
    customer_segment: 'returning',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 08:30',
    ml_result: {
      success_probability: 0.64,
      shap_contributions: [
        { feature: 'is_recurring', impact: 0.15 },
      ],
    },
    customer_message: 'Your Apple One subscription retry is scheduled for optimal payday authorization window.',
    compliance_status: 'compliant',
    attempt_timeline: [
      {
        attempt_number: 1,
        attempt_timestamp: '2026-08-29 08:30',
        channel: 'auto_retry',
        intervention_type: 'Direct Gateway Re-auth',
        outcome: 'fail',
        amount: 999,
        reason_or_stopping: 'Bank issuer security decline',
        compliance_flags: 'Compliant',
      },
      {
        attempt_number: 2,
        attempt_timestamp: '2026-08-30 08:30',
        channel: 'email_prompt',
        intervention_type: 'Customer Action Email Link',
        outcome: 'fail',
        amount: 999,
        reason_or_stopping: 'Awaiting customer card update',
        compliance_flags: 'Compliant',
      },
    ],
  },
  {
    transaction_id: 'txn_rzp_9901',
    merchant_name: 'Salesforce Enterprise Hub',
    merchant_category: 'cloud_saas',
    amount: 45000,
    status: 'escalated_to_human',
    failure_reason: 'issuer_declined',
    payment_method: 'card',
    customer_segment: 'high_value',
    attempt_count: 4,
    max_attempts: 4,
    date: '2026-08-30 11:20',
    ml_result: {
      success_probability: 0.18,
      shap_contributions: [
        { feature: 'attempt_number', impact: -0.45 },
      ],
    },
    customer_message: 'Your high-value Enterprise account has been routed to our Priority Human Accounts Desk for personal assistance.',
    compliance_status: 'escalated_to_human',
    attempt_timeline: [
      {
        attempt_number: 1,
        attempt_timestamp: '2026-08-27 10:00',
        channel: 'auto_retry',
        intervention_type: 'Direct Re-auth',
        outcome: 'fail',
        amount: 45000,
        reason_or_stopping: 'Bank decline',
        compliance_flags: 'Compliant',
      },
      {
        attempt_number: 2,
        attempt_timestamp: '2026-08-28 10:00',
        channel: 'email_prompt',
        intervention_type: 'Invoice Payment Link',
        outcome: 'fail',
        amount: 45000,
        reason_or_stopping: 'Link unclicked',
        compliance_flags: 'Compliant',
      },
      {
        attempt_number: 3,
        attempt_timestamp: '2026-08-29 10:00',
        channel: 'sms_prompt',
        intervention_type: 'Priority SMS Alert',
        outcome: 'fail',
        amount: 45000,
        reason_or_stopping: 'Bank corporate limit reached',
        compliance_flags: 'Compliant',
      },
      {
        attempt_number: 4,
        attempt_timestamp: '2026-08-30 11:20',
        channel: 'support_desk',
        intervention_type: 'Human Key Account Manager Handoff',
        outcome: 'escalated_to_human',
        amount: 45000,
        reason_or_stopping: 'Max 4 automated attempts exhausted -> VIP human recovery desk assigned',
        compliance_flags: 'Escalated to Human Agent',
      },
    ],
  },
  {
    transaction_id: 'txn_rzp_9902',
    merchant_name: 'Urban Company Pro',
    merchant_category: 'services',
    amount: 1299,
    status: 'dnd_blocked',
    failure_reason: 'insufficient_funds',
    payment_method: 'upi',
    customer_segment: 'returning',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-30 10:05',
    ml_result: {
      success_probability: 0.0,
      shap_contributions: [
        { feature: 'dnd_active', impact: -0.99 },
      ],
    },
    customer_message: 'Automated contact withheld as customer is registered on national TRAI DND registry.',
    compliance_status: 'dnd_restricted',
    attempt_timeline: [
      {
        attempt_number: 1,
        attempt_timestamp: '2026-08-30 10:05',
        channel: 'no_outbound',
        intervention_type: 'DND / Regulatory Check',
        outcome: 'compliance_hold',
        amount: 1299,
        reason_or_stopping: 'Suppressed automated SMS/call due to National DND / Consent Revocation registry',
        compliance_flags: 'DND Restricted',
      },
    ],
  },
  {
    transaction_id: 'txn_rzp_9903',
    merchant_name: 'Hotstar VIP Sports',
    merchant_category: 'subscription',
    amount: 899,
    status: 'quiet_hours_held',
    failure_reason: 'insufficient_funds',
    payment_method: 'card',
    customer_segment: 'new',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-29 23:45',
    ml_result: {
      success_probability: 0.72,
      shap_contributions: [
        { feature: 'is_near_payday', impact: 0.20 },
      ],
    },
    customer_message: 'Recovery notification scheduled for compliant morning contact window (09:00 AM IST).',
    compliance_status: 'quiet_hours_held',
    attempt_timeline: [
      {
        attempt_number: 1,
        attempt_timestamp: '2026-08-29 23:45',
        channel: 'email_prompt',
        intervention_type: 'Quiet Hours Compliance Delay',
        outcome: 'pending',
        amount: 899,
        reason_or_stopping: 'Contact suppressed between 8:00 PM and 9:00 AM IST. Next dispatch: 09:00 AM IST.',
        compliance_flags: 'Quiet Hours Held (23:45 IST)',
      },
    ],
  },
  {
    transaction_id: 'txn_rzp_6542',
    merchant_name: 'Spotify Premium',
    merchant_category: 'subscription',
    amount: 119,
    status: 'recovered',
    failure_reason: 'insufficient_funds',
    payment_method: 'upi',
    customer_segment: 'new',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-30 08:10',
    ml_result: {
      success_probability: 0.79,
      shap_contributions: [
        { feature: 'is_near_payday', impact: 0.28 },
      ],
    },
    customer_message: 'Your Spotify AutoPay UPI mandate was successfully processed on attempt 2.',
    compliance_status: 'compliant',
    attempt_timeline: [
      {
        attempt_number: 1,
        attempt_timestamp: '2026-08-30 08:10',
        channel: 'auto_retry',
        intervention_type: 'UPI Mandate Re-trigger',
        outcome: 'success',
        amount: 119,
        reason_or_stopping: 'Recovered via UPI autopay queue',
        compliance_flags: 'Compliant',
      },
    ],
  },
  {
    transaction_id: 'txn_rzp_5429',
    merchant_name: 'Uber Technologies',
    merchant_category: 'mobility',
    amount: 450,
    status: 'failed',
    failure_reason: 'card_stolen',
    payment_method: 'card',
    customer_segment: 'new',
    attempt_count: 1,
    max_attempts: 1,
    date: '2026-08-30 07:55',
    ml_result: {
      success_probability: 0.02,
      shap_contributions: [
        { feature: 'card_stolen_rule', impact: -0.85 },
      ],
    },
    customer_message: 'Payment declined due to issuer security flag. Please update payment method.',
    compliance_status: 'compliant',
    attempt_timeline: [
      {
        attempt_number: 1,
        attempt_timestamp: '2026-08-30 07:55',
        channel: 'no_outbound',
        intervention_type: 'Fraud & Hard-Fail Circuit Breaker',
        outcome: 'fail',
        amount: 450,
        reason_or_stopping: 'Hard-fail short-circuit: Card Stolen flag. Zero automatic retries allowed.',
        compliance_flags: 'Compliant (Fraud Safety)',
      },
    ],
  },
  {
    transaction_id: 'txn_rzp_4318',
    merchant_name: 'Notion Enterprise SaaS',
    merchant_category: 'cloud_saas',
    amount: 5499,
    status: 'recovered',
    failure_reason: 'do_not_honor',
    payment_method: 'card',
    customer_segment: 'high_value',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 07:20',
    ml_result: {
      success_probability: 0.83,
      shap_contributions: [
        { feature: 'historical_failure_rate', impact: 0.22 },
      ],
    },
    customer_message: 'Your Notion workspace renewal payment of ₹5,499 has been successfully recovered.',
    compliance_status: 'compliant',
    attempt_timeline: [
      {
        attempt_number: 1,
        attempt_timestamp: '2026-08-29 07:20',
        channel: 'auto_retry',
        intervention_type: 'Direct Re-auth',
        outcome: 'fail',
        amount: 5499,
        reason_or_stopping: 'Issuer soft decline (Do not honor)',
        compliance_flags: 'Compliant',
      },
      {
        attempt_number: 2,
        attempt_timestamp: '2026-08-30 07:20',
        channel: 'email_prompt',
        intervention_type: 'Smart Card Refresh Prompt',
        outcome: 'success',
        amount: 5499,
        reason_or_stopping: 'Payment cleared on customer card re-authentication',
        compliance_flags: 'Compliant',
      },
    ],
  },
]

export const SHARED_METRICS = {
  RECOVERED_ARR: 1119500,
  AT_RISK_ARR: 176200,
  TOTAL_FAILED_ARR: 1420500,
  RECOVERY_RATE: 0.864, // 86.4%
  TOTAL_FAILURES: 1240,
  HARD_FAILS: 148,
  RECOVERED_COUNT: 944,
}

export const MOCK_ANALYTICS_SUMMARY = {
  funnel: {
    total_failed: 1240,
    total_failures: 1240,
    hard_failed: 148,
    hard_fails_skipped: 148,
    eligible_for_retry: 1092,
    recovered: 944,
    retrying: 148,
    churned: 148,
    recovery_rate: 0.864,
  },
  revenue: {
    total_failed_arr: 1420500,
    hard_fail_arr: 124800,
    salvageable_arr: 1295700,
    recovered: 1119500,
    at_risk: 176200,
    recovery_revenue_rate: 0.864,
    currency: 'INR',
  },
  recovery_by_reason: {
    insufficient_funds: 0.892,
    issuer_declined: 0.838,
    network_timeout: 0.943,
    do_not_honor: 0.704,
    card_stolen: 0.0,
    card_expired: 0.0,
    account_closed: 0.0,
  },
  recovery_by_attempt: [
    { attempt_number: 1, recovery_rate: 0.62, n_attempts: 1092 },
    { attempt_number: 2, recovery_rate: 0.78, n_attempts: 415 },
    { attempt_number: 3, recovery_rate: 0.86, n_attempts: 91 },
    { attempt_number: 4, recovery_rate: 0.89, n_attempts: 12 },
  ],
  global_feature_importance: [
    { feature: 'is_near_payday', importance: 0.28 },
    { feature: 'time_since_last_attempt_hours', importance: 0.22 },
    { feature: 'historical_failure_rate', importance: 0.18 },
    { feature: 'customer_segment', importance: 0.14 },
    { feature: 'payment_method_upi', importance: 0.10 },
    { feature: 'is_recurring', importance: 0.08 },
  ],
  method_breakdown: [
    { method: 'card', total: 620, recovered: 532, rate: 0.858, arr_recovered: 712000 },
    { method: 'upi', total: 440, recovered: 391, rate: 0.889, arr_recovered: 298500 },
    { method: 'netbanking', total: 180, recovered: 153, rate: 0.850, arr_recovered: 109000 },
  ],
  failure_breakdown: [
    { reason: 'insufficient_funds', count: 480, recovered: 428, rate: 0.892 },
    { reason: 'issuer_declined', count: 260, recovered: 218, rate: 0.838 },
    { reason: 'network_timeout', count: 210, recovered: 198, rate: 0.943 },
    { reason: 'do_not_honor', count: 142, recovered: 100, rate: 0.704 },
    { reason: 'card_stolen', count: 68, recovered: 0, rate: 0.0 },
    { reason: 'card_expired', count: 45, recovered: 0, rate: 0.0 },
    { reason: 'account_closed', count: 35, recovered: 0, rate: 0.0 },
  ],
}

export const MOCK_CHECKOUT_EVENTS = [
  {
    checkout_id: 'chk_rzp_9102',
    customer_name: 'Rohan Sharma',
    customer_email: 'rohan.s@gmail.com',
    customer_phone: '+91 98201 44521',
    cart_value: 4299.0,
    items: ['Logitech MX Master 3S', 'Ergonomic Desk Mat'],
    abandoned_at_minutes_ago: 18,
    abandonment_stage: 'payment_step',
    recovery_channel: 'whatsapp',
    discount_offered_pct: 5,
    recovery_link: 'https://pay.rzp.io/chk_9102?rec=wa5',
    status: 'recovered',
    recovered_amount: 4084.05,
  },
  {
    checkout_id: 'chk_rzp_8471',
    customer_name: 'Pooja Hegde',
    customer_email: 'pooja.h@outlook.com',
    customer_phone: '+91 97112 88402',
    cart_value: 1899.0,
    items: ['Organic Protein Blend 1kg'],
    abandoned_at_minutes_ago: 35,
    abandonment_stage: 'address_step',
    recovery_channel: 'email',
    discount_offered_pct: 10,
    recovery_link: 'https://pay.rzp.io/chk_8471?rec=em10',
    status: 'sent_reminder',
    recovered_amount: 0.0,
  },
  {
    checkout_id: 'chk_rzp_7294',
    customer_name: 'Aditya Verma',
    customer_email: 'aditya.v@zenith.in',
    customer_phone: '+91 99403 11849',
    cart_value: 14999.0,
    items: ['Sony WH-1000XM5 ANC Headphones'],
    abandoned_at_minutes_ago: 5,
    abandonment_stage: 'payment_step',
    recovery_channel: 'whatsapp',
    discount_offered_pct: 5,
    recovery_link: 'https://pay.rzp.io/chk_7294?rec=wa5',
    status: 'pending',
    recovered_amount: 0.0,
  },
  {
    checkout_id: 'chk_rzp_6108',
    customer_name: 'Sunita Menon',
    customer_email: 'sunita.m@gmail.com',
    customer_phone: '+91 94451 90214',
    cart_value: 850.0,
    items: ['Artisan Coffee Beans 500g'],
    abandoned_at_minutes_ago: 90,
    abandonment_stage: 'coupon_applied',
    recovery_channel: 'sms',
    discount_offered_pct: 8,
    recovery_link: 'https://pay.rzp.io/chk_6108?rec=sms8',
    status: 'recovered',
    recovered_amount: 782.0,
  },
  {
    checkout_id: 'chk_rzp_5023',
    customer_name: 'Karan Malhotra',
    customer_email: 'karan.m@techpulse.io',
    customer_phone: '+91 98840 23119',
    cart_value: 7200.0,
    items: ['Smart Standing Desk Converter'],
    abandoned_at_minutes_ago: 240,
    abandonment_stage: 'payment_step',
    recovery_channel: 'whatsapp',
    discount_offered_pct: 7,
    recovery_link: 'https://pay.rzp.io/chk_5023?rec=wa7',
    status: 'expired',
    recovered_amount: 0.0,
  },
]

export const MOCK_INVOICES = [
  {
    invoice_id: 'inv_corp_1042',
    client_name: 'Zenith Cloud Infrastructure',
    client_category: 'Enterprise SaaS',
    amount: 145000.0,
    due_date: '2026-07-15',
    days_overdue: 46,
    aging_bucket: '31-60 days',
    chaser_stage: 'stage_3_urgent_notice',
    last_action_timestamp: '2026-08-28 11:30',
    next_action_due: '2026-09-02 (Formal Notice)',
    status: 'overdue',
    disputed: false,
  },
  {
    invoice_id: 'inv_corp_1089',
    client_name: 'BlueDart Hyperlogistics Ltd',
    client_category: 'Logistics & Supply',
    amount: 89000.0,
    due_date: '2026-08-10',
    days_overdue: 20,
    aging_bucket: '0-30 days',
    chaser_stage: 'stage_2_firm_followup',
    last_action_timestamp: '2026-08-25 15:45',
    next_action_due: '2026-09-01 (Call Scheduled)',
    status: 'overdue',
    disputed: false,
  },
  {
    invoice_id: 'inv_corp_0954',
    client_name: 'OmniRetail D2C Brands',
    client_category: 'E-Commerce',
    amount: 320000.0,
    due_date: '2026-05-20',
    days_overdue: 102,
    aging_bucket: '90+ days',
    chaser_stage: 'stage_5_human_legal_escalation',
    last_action_timestamp: '2026-08-20 09:00',
    next_action_due: 'Legal Desk Review',
    status: 'escalated_to_legal',
    disputed: true,
  },
  {
    invoice_id: 'inv_corp_1120',
    client_name: 'ScaleAI Analytics India',
    client_category: 'AI Technology',
    amount: 64000.0,
    due_date: '2026-08-22',
    days_overdue: 8,
    aging_bucket: '0-30 days',
    chaser_stage: 'stage_1_gentle_reminder',
    last_action_timestamp: '2026-08-29 10:15',
    next_action_due: '2026-09-05 (Auto Follow-up)',
    status: 'overdue',
    disputed: false,
  },
  {
    invoice_id: 'inv_corp_0998',
    client_name: 'FinEdge Banking Solutions',
    client_category: 'Fintech Enterprise',
    amount: 210000.0,
    due_date: '2026-06-30',
    days_overdue: 61,
    aging_bucket: '61-90 days',
    chaser_stage: 'stage_4_account_hold',
    last_action_timestamp: '2026-08-26 14:00',
    next_action_due: 'Account Suspension Pending',
    status: 'overdue',
    disputed: false,
  },
]
