// lib/merchantData.js — Realistic Fintech Merchant Data & Branding

export const REALISTIC_TRANSACTIONS = [
  {
    transaction_id: 'txn_rzp_9842',
    merchant_name: 'Netflix India',
    merchant_category: 'subscription',
    amount: 649,
    status: 'recovered',
    failure_reason: 'insufficient_funds',
    payment_method: 'card',
    customer_segment: 'returning',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 09:42',
    ml_result: { success_probability: 0.88, shap_contributions: [{ feature: 'is_near_payday', impact: 0.24 }, { feature: 'historical_failure_rate', impact: 0.12 }] },
    customer_message: 'Your Netflix subscription payment of ₹649 was automatically recovered. No action needed.',
  },
  {
    transaction_id: 'txn_rzp_8731',
    merchant_name: 'Amazon Web Services',
    merchant_category: 'cloud_saas',
    amount: 18490,
    status: 'recovered',
    failure_reason: 'processing_error',
    payment_method: 'netbanking',
    customer_segment: 'high_value',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-30 09:15',
    ml_result: { success_probability: 0.94, shap_contributions: [{ feature: 'time_since_last_attempt_hours', impact: 0.31 }] },
    customer_message: 'Your AWS monthly cloud infrastructure invoice was successfully re-authorized by Razorpay Recovery Engine.',
  },
  {
    transaction_id: 'txn_rzp_7650',
    merchant_name: 'Apple Services',
    merchant_category: 'digital_goods',
    amount: 999,
    status: 'retrying',
    failure_reason: 'issuer_declined',
    payment_method: 'card',
    customer_segment: 'returning',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 08:30',
    ml_result: { success_probability: 0.64, shap_contributions: [{ feature: 'is_recurring', impact: 0.15 }] },
    customer_message: 'Your Apple One subscription retry is scheduled for optimal payday authorization window.',
  },
  {
    transaction_id: 'txn_rzp_6542',
    merchant_name: 'Spotify Premium',
    merchant_category: 'subscription',
    amount: 119,
    status: 'recovered',
    failure_reason: 'insufficient_funds',
    payment_method: 'upi',
    customer_segment: 'new',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-30 08:10',
    ml_result: { success_probability: 0.79, shap_contributions: [{ feature: 'is_near_payday', impact: 0.28 }] },
    customer_message: 'Your Spotify AutoPay UPI mandate was successfully processed on attempt 2.',
  },
  {
    transaction_id: 'txn_rzp_5429',
    merchant_name: 'Uber Technologies',
    merchant_category: 'mobility',
    amount: 450,
    status: 'failed',
    failure_reason: 'card_stolen',
    payment_method: 'card',
    customer_segment: 'new',
    attempt_count: 1,
    max_attempts: 1,
    date: '2026-08-30 07:55',
    ml_result: { success_probability: 0.02, shap_contributions: [{ feature: 'card_stolen_rule', impact: -0.85 }] },
    customer_message: 'Payment declined due to issuer security flag. Please update payment method.',
  },
  {
    transaction_id: 'txn_rzp_4318',
    merchant_name: 'Notion Enterprise SaaS',
    merchant_category: 'cloud_saas',
    amount: 5499,
    status: 'recovered',
    failure_reason: 'do_not_honor',
    payment_method: 'card',
    customer_segment: 'high_value',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 07:20',
    ml_result: { success_probability: 0.83, shap_contributions: [{ feature: 'historical_failure_rate', impact: 0.22 }] },
    customer_message: 'Your Notion workspace renewal payment of ₹5,499 has been successfully recovered.',
  },
  {
    transaction_id: 'txn_rzp_3280',
    merchant_name: 'Swiggy One',
    merchant_category: 'membership',
    amount: 299,
    status: 'recovered',
    failure_reason: 'network_timeout',
    payment_method: 'upi',
    customer_segment: 'returning',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-30 06:45',
    ml_result: { success_probability: 0.91, shap_contributions: [{ feature: 'payment_method_upi', impact: 0.35 }] },
    customer_message: 'Swiggy One membership renewal succeeded via automated smart retry.',
  },
  {
    transaction_id: 'txn_rzp_2194',
    merchant_name: 'Flipkart VIP',
    merchant_category: 'ecommerce',
    amount: 1499,
    status: 'retrying',
    failure_reason: 'insufficient_funds',
    payment_method: 'card',
    customer_segment: 'returning',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-30 06:15',
    ml_result: { success_probability: 0.74, shap_contributions: [{ feature: 'is_near_payday', impact: 0.18 }] },
    customer_message: 'Smart retry cycle 2 queued for execution near customer payday window.',
  },
  {
    transaction_id: 'txn_rzp_1985',
    merchant_name: 'GitHub Enterprise',
    merchant_category: 'developer_tools',
    amount: 8200,
    status: 'recovered',
    failure_reason: 'network_timeout',
    payment_method: 'card',
    customer_segment: 'high_value',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-30 05:30',
    ml_result: { success_probability: 0.96, shap_contributions: [{ feature: 'customer_segment_high_value', impact: 0.29 }] },
    customer_message: 'GitHub Copilot Enterprise seats invoice cleared on first autonomous backoff attempt.',
  },
  {
    transaction_id: 'txn_rzp_1872',
    merchant_name: 'Microsoft 365',
    merchant_category: 'productivity',
    amount: 4899,
    status: 'recovered',
    failure_reason: 'issuer_declined',
    payment_method: 'card',
    customer_segment: 'returning',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 04:50',
    ml_result: { success_probability: 0.85, shap_contributions: [{ feature: 'time_since_first_failure_hours', impact: 0.21 }] },
    customer_message: 'Microsoft 365 Business Family license re-authorized cleanly with issuer.',
  },
  {
    transaction_id: 'txn_rzp_1763',
    merchant_name: 'Zomato Gold',
    merchant_category: 'membership',
    amount: 199,
    status: 'recovered',
    failure_reason: 'insufficient_funds',
    payment_method: 'upi',
    customer_segment: 'returning',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 04:10',
    ml_result: { success_probability: 0.77, shap_contributions: [{ feature: 'is_near_payday', impact: 0.25 }] },
    customer_message: 'Zomato Gold dining subscription renewal payment recovered successfully via UPI.',
  },
  {
    transaction_id: 'txn_rzp_1654',
    merchant_name: 'Figma Pro Workspace',
    merchant_category: 'cloud_saas',
    amount: 3200,
    status: 'recovered',
    failure_reason: 'processing_error',
    payment_method: 'card',
    customer_segment: 'high_value',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-30 03:25',
    ml_result: { success_probability: 0.92, shap_contributions: [{ feature: 'is_recurring', impact: 0.33 }] },
    customer_message: 'Figma Organization design editor subscription recovered automatically.',
  },
  {
    transaction_id: 'txn_rzp_1545',
    merchant_name: 'Canva Pro Annual',
    merchant_category: 'design_tools',
    amount: 3999,
    status: 'retrying',
    failure_reason: 'insufficient_funds',
    payment_method: 'upi',
    customer_segment: 'returning',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 02:40',
    ml_result: { success_probability: 0.69, shap_contributions: [{ feature: 'is_near_payday', impact: 0.16 }] },
    customer_message: 'Canva Pro design suite subscription retry scheduled for 24h spacing window.',
  },
  {
    transaction_id: 'txn_rzp_1436',
    merchant_name: 'Shopify Advanced Store',
    merchant_category: 'ecommerce',
    amount: 22400,
    status: 'recovered',
    failure_reason: 'do_not_honor',
    payment_method: 'netbanking',
    customer_segment: 'high_value',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 01:55',
    ml_result: { success_probability: 0.89, shap_contributions: [{ feature: 'customer_segment_high_value', impact: 0.38 }] },
    customer_message: 'Shopify merchant monthly store platform plan recovered via intelligent netbanking routing.',
  },
  {
    transaction_id: 'txn_rzp_1327',
    merchant_name: 'Adobe Creative Cloud',
    merchant_category: 'creative_suite',
    amount: 4230,
    status: 'recovered',
    failure_reason: 'issuer_declined',
    payment_method: 'card',
    customer_segment: 'returning',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-30 01:10',
    ml_result: { success_probability: 0.82, shap_contributions: [{ feature: 'time_since_last_attempt_hours', impact: 0.27 }] },
    customer_message: 'Adobe Creative Cloud All Apps membership invoice successfully settled.',
  },
  {
    transaction_id: 'txn_rzp_1218',
    merchant_name: 'Vercel Enterprise Pro',
    merchant_category: 'cloud_saas',
    amount: 16500,
    status: 'recovered',
    failure_reason: 'processing_error',
    payment_method: 'card',
    customer_segment: 'high_value',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-30 00:25',
    ml_result: { success_probability: 0.95, shap_contributions: [{ feature: 'customer_segment_high_value', impact: 0.42 }] },
    customer_message: 'Vercel edge serverless deployment infrastructure plan invoice auto-cleared.',
  },
  {
    transaction_id: 'txn_rzp_1109',
    merchant_name: 'Hotstar Super Disney+',
    merchant_category: 'subscription',
    amount: 899,
    status: 'recovered',
    failure_reason: 'network_timeout',
    payment_method: 'upi',
    customer_segment: 'returning',
    attempt_count: 1,
    max_attempts: 4,
    date: '2026-08-29 23:40',
    ml_result: { success_probability: 0.88, shap_contributions: [{ feature: 'payment_method_upi', impact: 0.31 }] },
    customer_message: 'Disney+ Hotstar 4K live sports streaming pass successfully re-authorized.',
  },
  {
    transaction_id: 'txn_rzp_1098',
    merchant_name: 'Atlassian Jira Cloud',
    merchant_category: 'productivity',
    amount: 7200,
    status: 'recovered',
    failure_reason: 'insufficient_funds',
    payment_method: 'card',
    customer_segment: 'high_value',
    attempt_count: 2,
    max_attempts: 4,
    date: '2026-08-29 22:50',
    ml_result: { success_probability: 0.84, shap_contributions: [{ feature: 'is_near_payday', impact: 0.22 }] },
    customer_message: 'Atlassian Jira & Confluence team billing reconciled seamlessly.',
  },
]

export const MOCK_ANALYTICS_SUMMARY = {
  funnel: {
    total_failures: 1240,
    hard_fails_skipped: 148,
    eligible_for_retry: 1092,
    recovered: 944,
    churned: 148,
    recovery_rate: 0.864,
  },
  revenue: {
    total_failed_arr: 1420500,
    hard_fail_arr: 124800,
    salvageable_arr: 1295700,
    recovered: 1119500,
    at_risk: 176200,
    recovery_revenue_rate: 0.864,
  },
  method_breakdown: [
    { method: 'card', total: 620, recovered: 532, rate: 0.858, arr_recovered: 712000 },
    { method: 'upi', total: 440, recovered: 391, rate: 0.889, arr_recovered: 298500 },
    { method: 'netbanking', total: 180, recovered: 153, rate: 0.850, arr_recovered: 109000 },
  ],
  failure_breakdown: [
    { reason: 'insufficient_funds', count: 480, recovered: 428, rate: 0.892 },
    { reason: 'issuer_declined', count: 260, recovered: 218, rate: 0.838 },
    { reason: 'network_timeout', count: 210, recovered: 198, rate: 0.943 },
    { reason: 'do_not_honor', count: 142, recovered: 100, rate: 0.704 },
    { reason: 'card_stolen', count: 68, recovered: 0, rate: 0.0 },
    { reason: 'card_expired', count: 45, recovered: 0, rate: 0.0 },
    { reason: 'account_closed', count: 35, recovered: 0, rate: 0.0 },
  ],
}

